version: '3.8'

services:

  app-db:
    container_name: app-db
    image: postgres:alpine
    volumes:
      - ./app_db/tableCreation.sql:/docker-entrypoint-initdb.d/tableCreation.sql
      - app-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin

  app:
    container_name: app
    build:
      context: ./app
      target: prod
    volumes:
      - app-external:/app/external
    environment:
      JAVA_TOOL_OPTIONS: > 
        -Dcom.sun.management.jmxremote.ssl=false 
        -Dcom.sun.management.jmxremote.authenticate=false 
        -Dcom.sun.management.jmxremote.port=5000 
        -Dcom.sun.management.jmxremote.rmi.port=5000 
        -Dcom.sun.management.jmxremote.host=0.0.0.0 
        -Djava.rmi.server.hostname=app
      POSTGRES_HOSTNAME: app-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    depends_on:
      - app-db
    ports:
      - 8080:8080

  zabbix-db:
    container_name: zabbix-db
    image: postgres:alpine
    volumes:
      - zabbix-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  zabbix-java-gateway:
    container_name: zabbix-java-gateway
    image: zabbix/zabbix-java-gateway:alpine-6.2-latest

  zabbix-server: 
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:alpine-6.2-latest
    environment:
      ZBX_HOSTNAME: zabbix-server
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      ZBX_JAVAGATEWAY_ENABLE: true
      ZBX_JAVAGATEWAY: zabbix-java-gateway
    depends_on:
      - zabbix-db
      - zabbix-java-gateway
    restart: unless-stopped

  zabbix-agent: 
    container_name: zabbix-agent
    image: zabbix/zabbix-agent:alpine-6.2-latest
    privileged: true
    environment:
      ZBX_HOSTNAME: zabbix-agent
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
    restart: unless-stopped
    
  zabbix-web-interface:
    container_name: zabbix-web-interface
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.2-latest
    environment:
      ZBX_HOSTNAME: zabbix-web-interface
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
    ports:
      - 80:8080
    restart: unless-stopped

volumes:
  app-db-data:
  app-external:
  zabbix-db-data:
