version: '3.8'

services:

  app-db:
    container_name: app-db
    image: postgres:alpine
    volumes:
      - ./app_db/tableCreation.sql:/docker-entrypoint-initdb.d/tableCreation.sql
      - app-db-data:/var/lib/postgresql/data
      - ./app_db/logs:/logs
    environment:
      POSTGRES_PASSWORD: admin
    command: >
      -c logging_collector=on
      -c log_directory=/logs
      -c log_filename=postgresql.log
      -c log_destination=csvlog
      -c log_statement=all

  app:
    container_name: app
    build:
      context: ./app
      target: prod
    volumes:
      - app-external:/app/external
    environment:
      JAVA_TOOL_OPTIONS: > 
        -Dcom.sun.management.jmxremote.ssl=false 
        -Dcom.sun.management.jmxremote.authenticate=false 
        -Dcom.sun.management.jmxremote.port=5000 
        -Dcom.sun.management.jmxremote.rmi.port=5000 
        -Dcom.sun.management.jmxremote.host=0.0.0.0 
        -Djava.rmi.server.hostname=app
      POSTGRES_HOSTNAME: app-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    depends_on:
      - app-db
    ports:
      - 8080:8080

  zabbix-db:
    container_name: zabbix-db
    image: postgres:alpine
    volumes:
      - zabbix-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  zabbix-java-gateway:
    container_name: zabbix-java-gateway
    image: zabbix/zabbix-java-gateway:alpine-6.2-latest

  zabbix-server: 
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:alpine-6.2-latest
    environment:
      ZBX_HOSTNAME: zabbix-server
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      ZBX_JAVAGATEWAY_ENABLE: true
      ZBX_JAVAGATEWAY: zabbix-java-gateway
    depends_on:
      - zabbix-db
      - zabbix-java-gateway
    restart: unless-stopped

  zabbix-agent: 
    container_name: zabbix-agent
    image: zabbix/zabbix-agent:alpine-6.2-latest
    privileged: true
    environment:
      ZBX_HOSTNAME: zabbix-agent
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
    restart: unless-stopped
    
  zabbix-web-interface:
    container_name: zabbix-web-interface
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.2-latest
    environment:
      ZBX_HOSTNAME: zabbix-web-interface
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
    ports:
      - 80:8080
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  postgres-exporter:
    container_name: postgres-exporter
    image: prometheuscommunity/postgres-exporter:latest
    environment:
      DATA_SOURCE_NAME: "postgresql://app:app@app-db:5432/postgres?sslmode=disable"
    depends_on:
      - app-db
      - prometheus

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes: 
      - ./grafana/data:/var/lib/grafana/
    ports:
      - 3000:3000
    depends_on:
      - postgres-exporter

  graylog-mongo:
    container_name: graylog-mongo
    image: bitnami/mongodb:latest
    volumes:
      - graylog-mongo-data:/bitnami/mongodb
    environment:
      MONGODB_ROOT_PASSWORD: 123
      MONGODB_USERNAME: graylog
      MONGODB_PASSWORD: graylog
      MONGODB_DATABASE: graylog
  
  graylog-elasticsearch:
    container_name: graylog-elasticsearch
    image: bitnami/elasticsearch:7.17.7
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - node.max_local_storage_nodes=3
      - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g

  graylog-filebeat:
    container_name: graylog-filebeat
    image: elastic/filebeat:8.5.1
    entrypoint: filebeat -e -strict.perms=false
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./app_db/logs:/var/app/log

  graylog:
    container_name: graylog
    image: graylog/graylog:4.3
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      # Password: admin
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_HTTP_EXTERNAL_URI: http://127.0.0.1:9000/
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
      GRAYLOG_ELASTICSEARCH_HOSTS: http://graylog-elasticsearch:9200
      GRAYLOG_MONGODB_URI: mongodb://graylog:graylog@graylog-mongo:27017/graylog
      GRAYLOG_MESSAGE_JOURNAL_MAX_SIZE: 128mb
      # Content pack options
      GRAYLOG_CONTENT_PACKS_AUTO_INSTALL: content-pack-a11181bd-ab8e-4a6b-8153-99452fe8a521-1.json
      GRAYLOG_CONTENT_PACKS_DIR: data/contentpacks
      GRAYLOG_CONTENT_PACKS_LOADER_ENABLED: true
    entrypoint: /usr/bin/tini -- wait-for-it graylog-elasticsearch:9200 --  /docker-entrypoint.sh 
    volumes:
      - ./graylog/contentpacks:/usr/share/graylog/data/contentpacks
    restart: always
    depends_on:
      - graylog-mongo
      - graylog-elasticsearch
      - graylog-filebeat
    ports:
      # Graylog web interface and REST API
      - 9000:9000

volumes:
  app-db-data:
  app-external:
  zabbix-db-data:
  graylog-mongo-data:
