version: '3.8'

services:
  app:
    build:
      context: ./app
      target: prod
    image: app
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - type: volume
        source: app-external
        target: /app/external

  postgres:
    container_name: app_bd
    image: postgres:my
    build:
      context: database/
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: db-source
        target: /var/lib/postgresql/data
    environment:
      PGPASSWORD: admin
      POSTGRES_PASSWORD: admin

  # pgAdmin:
  #   container_name: app_pgAdmin
  #   image: dpage/pgadmin4
  #   links:
  #     - postgres
  #   ports:
  #     - 5050:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.admin
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_LISTEN_PORT: 80
  #   volumes:
  #     - type: volume
  #       source: pg-admin
  #       target: /var/lib/pgadmin

volumes:
  db-source:
    name: db-source
  # pg-admin:
  #   name: pg-admin
  app-external:
    name: app-external
