resources:
  images:
    path: "/app/external"

spring :
  resources:
    static-locations:
    - "classpath:/static/"
    - "file:/app/external/"
  datasource :
    url : jdbc:postgresql://postgres:5432/postgres
    username : java
    password : java
    driver-class-name : org.postgresql.Driver

  jpa :
    database : postgresql
    database-platform : org.hibernate.dialect.PostgreSQL10Dialect