resources:
  images:
    path: "C:\\Users\\is-in\\Desktop\\Учеба\\external"

spring :
  resources:
    static-locations:
    - "classpath:/static/"
    - "file:/Users/is-in/Desktop/Учеба/external/"
  datasource :
    url : jdbc:postgresql://localhost:7000/postgres
    username : java
    password : java
    driver-class-name : org.postgresql.Driver

  jpa :
    database : postgresql
    database-platform : org.hibernate.dialect.PostgreSQL10Dialect